import { mutationGeneric, queryGeneric } from "convex/server";
import { v } from "convex/values";
import { requireOwnedBrain } from "./auth";

const TASK_HEARTBEAT_BODY = [
  "# Skippy Task Heartbeat",
  "",
  "Check Skippy for requested Ready agent tasks using `list_requested_ready_tasks`.",
  "",
  "If no tasks are queued, stop quietly.",
  "",
  "If tasks are queued, process all queued tasks that can be completed safely in this wake.",
  "",
  "For each task:",
  "- Before doing meaningful work, mark the task in progress.",
  "- Execute it according to its execution brief and acceptance criteria.",
  "- Run relevant verification.",
  "- Report the result back to Skippy with `record_task_result` so the task moves to In Review.",
  "",
  "For coding tasks in projects with a GitHub repo:",
  "- Create or reuse a dedicated branch named `agent/task-<taskId>-<slug>`.",
  "- Commit only task-owned files.",
  "- Push the branch.",
  "- Create or reuse a GitHub PR.",
  "- Include `gitBranchName`, `prUrl`, `prNumber`, `prStatus`, and `resultUrl` when recording the task result.",
  "",
  "If the project has no repo configured, do not attempt branch/PR work; record a clear result or blocker message instead.",
  "",
  "Do not mark tasks done unless the owner explicitly requested automatic completion.",
  "",
  "If a task becomes blocked or unsafe to continue, record a clear result or status for that task and continue with the next queued task only when it is independent and safe to do so.",
].join("\n");

const TASK_HEARTBEAT_USAGE_DESCRIPTION =
  "Use this skill when you want an AI harness like Codex, Claude, or Hermes to periodically check Skippy for Ready agent tasks and report results back to Skippy.";

const TASK_HEARTBEAT_SCHEDULER_INSTRUCTIONS = [
  "If you support Skippy MCP prompts:",
  "Use the prompt `skippy_task_heartbeat`.",
  "",
  "If you do not support Skippy MCP prompts but do support Skippy MCP tools:",
  "Call `get_skill` with slug `task-heartbeat`",
  "",
  "If neither of those work, load the Skippy skill at:",
  "https://skippy.jeffschram.dev/skills/task-heartbeat",
].join("\n");

const HARNESS_BOOTSTRAP_BODY = [
  "# Skippy Harness Bootstrap",
  "",
  "You are an AI harness connected to Skippy MCP. Skippy is the user's portable second brain, project manager, and review layer. The harness supplies context and execution; Skippy stores accepted knowledge, tasks, project state, source references, and task results.",
  "",
  "## Key URLs And Endpoints",
  "",
  "- Production app: https://skippy.jeffschram.dev",
  "- Production MCP endpoint: https://skippy.jeffschram.dev/api/mcp",
  "- Local development app/MCP endpoint: http://localhost:3000 and http://localhost:3000/api/mcp",
  "",
  "## Auth Expectations",
  "",
  "- Use a Skippy MCP bearer token generated by the signed-in user.",
  "- Never print, store in chat, commit, or log raw tokens.",
  "- A token maps to one Skippy brain through Convex `mcpTokens`.",
  "",
  "## First 5 Minutes",
  "",
  "1. Confirm you can access Skippy MCP tools.",
  "2. Load this bootstrap skill and, when useful, `skippy_task_heartbeat`.",
  "3. Call `get_current_context` if the user says this project, here, or current project.",
  "4. Use `list_ready_tasks` or `list_requested_ready_tasks` before executing agent work.",
  "5. Fetch details with `get_task_brief`, do the work, verify it, then call `record_task_result`.",
  "",
  "## Core Workflow",
  "",
  "- Proposed tasks stay Proposed until promoted/briefed by Skippy or the owner.",
  "- Ready is the agent queue; requested Ready tasks are the safest automation queue.",
  "- Agent work should end in `in_review` unless the owner explicitly allows automatic completion.",
  "- Coding tasks should produce a branch, verification, and PR when the project has a GitHub repo.",
  "",
  "## Key Tools",
  "",
  "- `get_current_context`: resolve active app route/project.",
  "- `create_task` / `create_project`: explicit user-created items.",
  "- `plan_project`: decompose accepted projects.",
  "- `list_ready_tasks` / `list_requested_ready_tasks`: find executable work.",
  "- `get_task_brief`: get the handoff brief.",
  "- `record_task_result`: report PR/artifact/result for review.",
  "- `get_skill`: load canonical Skippy-hosted skills by slug.",
  "- `get_importance_rubric`, `ingest_object`, `record_memory`, `capture_thought`: capture useful second-brain context.",
  "",
  "## Canonical References",
  "",
  "- `README.md`: repo overview.",
  "- `docs/codex-heartbeat.md`: Ready task heartbeat contract.",
  "- `docs/onboarding-harness-verification.md`: onboarding and connection verification design.",
  "- `skills/skippy-harness/SKILL.md`: local Codex skill for Skippy harness behavior.",
  "- `apps/mcp-server/src/mcp-server.ts`: MCP prompts/resources/tools.",
  "- `apps/web/app/api/mcp/route.ts`: remote MCP endpoint.",
  "- `convex/mcpTokens.ts`: bearer-token auth.",
  "- `convex/projects.ts`: project/task planning and result state.",
].join("\n");

const HARNESS_BOOTSTRAP_USAGE_DESCRIPTION =
  "Use this skill when connecting a new AI harness so it can quickly understand Skippy, the MCP endpoint, auth expectations, and the project/task workflow.";

const HARNESS_BOOTSTRAP_SCHEDULER_INSTRUCTIONS = [
  "If you support Skippy MCP prompts:",
  "Use the prompt `skippy_harness_bootstrap`.",
  "",
  "If you do not support Skippy MCP prompts but do support Skippy MCP tools:",
  "Call `get_skill` with slug `harness-bootstrap`.",
  "",
  "If neither of those work, load the Skippy skill at:",
  "https://skippy.jeffschram.dev/skills/harness-bootstrap",
].join("\n");

const AGENDA_INGESTION_BODY = [
  "# Skippy Agenda Ingestion",
  "",
  "You are running as the **Agenda Agent** (role key: `agenda`). The role is defined by this skill; the harness executing it (Codex, Claude, Hermes) is interchangeable. See `docs/agents.md` for the agents-as-roles architecture.",
  "",
  "The job: read the user's sources, apply the importance rubric, store what matters as accepted Skippy objects with provenance, and refresh the focus summary. Coordinate through shared Skippy state only — never assume another agent will be messaged.",
  "",
  "## Run Protocol",
  "",
  "1. Call `update_source_sync_status` with status `running`, harness set to your engine name, and the sources in scope (for example `gmail`, `calendar`, `imessage`). Include `metadata.role: \"agenda\"`.",
  "2. Call `get_importance_rubric` and read `renderedText` before judging any item.",
  "3. Read the sources in scope since the last successful run. Also call `list_quick_captures` for pending Home quick captures — they are part of every ingestion pass.",
  "4. For each item, decide under the rubric:",
  "   - **Store**: clear deadline, money, commitment, relationship, focus-relevant, or security signal. Use `ingest_object` with a specific `rubricDecision` and at least one `sourceRef` (IDs, timestamp, one-line summary, shortest useful excerpt — never raw bodies).",
  "   - **Review**: genuinely uncertain but inspectable later. Use `submit_candidate_object`.",
  "   - **Ignore**: marketing, newsletters, shipping notices, generic confirmations, transient alerts, secrets/credentials. Write nothing.",
  "   - Durable preferences, decisions, or principles evidenced by a source go through `record_memory` / `record_decision` / `record_principle` with provenance.",
  "5. For each pending quick capture, create the useful objects, then call `mark_quick_capture_handled` with `processed` (listing `relatedEntityRefs` you created) or `discarded` with a short note.",
  "6. Call `refresh_focus_summary` so the dashboard reflects the new state.",
  "7. Call `record_ingestion_run` with sources checked, object counts, errors, and `metadata.role: \"agenda\"`.",
  "8. Call `update_source_sync_status` with `completed` (or `failed` plus short error summaries). For long runs, heartbeat with `lastHeartbeatAt` while work continues.",
  "",
  "## Attribution",
  "",
  "Every run this skill performs is attributed to the `agenda` role, separate from the harness. Always set `metadata.role: \"agenda\"` on `record_ingestion_run` and `update_source_sync_status` so runs read as \"the Agenda Agent ran on <harness>\".",
  "",
  "## Boundaries",
  "",
  "- Ingestion and memory tools only: do not execute agent tasks, write financial data, or perform external side effects. Anything with side effects belongs in the approval-gated pending-actions flow.",
  "- Store distilled summaries with source refs, not raw private dumps.",
  "- Sensitive items (health, legal, family, private third-party facts) are never silently stored; queue for review or skip.",
  "- If a source is unreachable, record the error on the run and continue with the remaining sources; never fail silently.",
].join("\n");

const AGENDA_INGESTION_USAGE_DESCRIPTION =
  "Use this skill for scheduled Agenda Agent runs: reading gmail/calendar/imessage and pending quick captures, applying the importance rubric, ingesting accepted objects with provenance, and refreshing the focus summary.";

const AGENDA_INGESTION_SCHEDULER_INSTRUCTIONS = [
  "If you support Skippy MCP prompts:",
  "Use the prompt `skippy_agenda_ingestion`.",
  "",
  "If you do not support Skippy MCP prompts but do support Skippy MCP tools:",
  "Call `get_skill` with slug `agenda-ingestion`",
  "",
  "If neither of those work, load the Skippy skill at:",
  "https://skippy.jeffschram.dev/skills/agenda-ingestion",
].join("\n");

const DEFAULT_SKILLS = [
  {
    slug: "task-heartbeat",
    title: "Task heartbeat",
    description: "Portable instructions for harnesses that execute requested Ready agent tasks from Skippy.",
    body: TASK_HEARTBEAT_BODY,
    usageDescription: TASK_HEARTBEAT_USAGE_DESCRIPTION,
    usageLeadIn: "In your harness scheduler paste the following:",
    schedulerInstructions: TASK_HEARTBEAT_SCHEDULER_INSTRUCTIONS,
    visibility: "public" as const,
    version: 1,
  },
  {
    slug: "harness-bootstrap",
    title: "Harness bootstrap",
    description: "Portable context pack that teaches a newly connected harness how Skippy works.",
    body: HARNESS_BOOTSTRAP_BODY,
    usageDescription: HARNESS_BOOTSTRAP_USAGE_DESCRIPTION,
    usageLeadIn: "Give a newly connected harness this instruction:",
    schedulerInstructions: HARNESS_BOOTSTRAP_SCHEDULER_INSTRUCTIONS,
    visibility: "public" as const,
    version: 1,
  },
  {
    slug: "agenda-ingestion",
    title: "Agenda ingestion",
    description:
      "The Agenda Agent's role skill: rubric-driven source ingestion with provenance, quick-capture handling, sync status, and focus refresh.",
    body: AGENDA_INGESTION_BODY,
    usageDescription: AGENDA_INGESTION_USAGE_DESCRIPTION,
    usageLeadIn: "In your harness scheduler paste the following:",
    schedulerInstructions: AGENDA_INGESTION_SCHEDULER_INSTRUCTIONS,
    visibility: "public" as const,
    version: 1,
  },
];

function fallbackSkill(slug: string) {
  return DEFAULT_SKILLS.find((skill) => skill.slug === slug) ?? null;
}

async function viewerBrainOrDefault(ctx: any) {
  const identity = await ctx.auth.getUserIdentity();
  if (identity) {
    try {
      const { brain } = await requireOwnedBrain(ctx);
      return brain;
    } catch {
      // Fall through to the first brain so public skill pages remain readable locally.
    }
  }
  return await ctx.db.query("brainInstances").first();
}

async function currentSkill(db: any, brainInstanceId: string, slug: string) {
  return await db
    .query("harnessSkills")
    .withIndex("by_brain_slug_current", (q: any) =>
      q.eq("brainInstanceId", brainInstanceId).eq("slug", slug).eq("isCurrent", true),
    )
    .first();
}

function toPublicSkill(skill: any, fallback?: (typeof DEFAULT_SKILLS)[number]) {
  return {
    _id: skill?._id,
    slug: skill?.slug ?? fallback?.slug,
    title: skill?.title ?? fallback?.title,
    description: skill?.description ?? fallback?.description,
    body: skill?.body ?? fallback?.body,
    usageDescription: skill?.usageDescription ?? fallback?.usageDescription,
    usageLeadIn: skill?.usageLeadIn ?? fallback?.usageLeadIn,
    schedulerInstructions: skill?.schedulerInstructions ?? fallback?.schedulerInstructions,
    visibility: skill?.visibility ?? fallback?.visibility ?? "public",
    version: skill?.version ?? fallback?.version ?? 1,
    isDefault: !skill,
    updatedAt: skill?.updatedAt,
  };
}

export const listSkills = queryGeneric({
  args: {},
  handler: async (ctx) => {
    const brain = await viewerBrainOrDefault(ctx);
    if (!brain) return DEFAULT_SKILLS.map((skill) => toPublicSkill(null, skill));

    const stored = await ctx.db
      .query("harnessSkills")
      .withIndex("by_brain_current", (q: any) => q.eq("brainInstanceId", brain._id).eq("isCurrent", true))
      .collect();
    const bySlug = new Map(stored.map((skill: any) => [skill.slug, skill]));
    const merged = DEFAULT_SKILLS.map((skill) => toPublicSkill(bySlug.get(skill.slug), skill));
    for (const skill of stored) {
      if (!DEFAULT_SKILLS.some((defaultSkill) => defaultSkill.slug === skill.slug)) {
        merged.push(toPublicSkill(skill));
      }
    }
    return merged.filter((skill) => skill.visibility === "public");
  },
});

export const getSkill = queryGeneric({
  args: { slug: v.string() },
  handler: async (ctx, args) => {
    const slug = args.slug.trim();
    const fallback = fallbackSkill(slug);
    const brain = await viewerBrainOrDefault(ctx);
    if (!brain) return fallback ? toPublicSkill(null, fallback) : null;
    const stored = await currentSkill(ctx.db, brain._id, slug);
    const skill = toPublicSkill(stored, fallback ?? undefined);
    return skill.slug && skill.visibility === "public" ? skill : null;
  },
});

export const getSkillForBrain = queryGeneric({
  args: { brainInstanceId: v.id("brainInstances"), slug: v.string() },
  handler: async (ctx, args) => {
    const slug = args.slug.trim();
    const fallback = fallbackSkill(slug);
    const stored = await currentSkill(ctx.db, args.brainInstanceId, slug);
    return toPublicSkill(stored, fallback ?? undefined);
  },
});

export const listSkillVersions = queryGeneric({
  args: { slug: v.string() },
  handler: async (ctx, args) => {
    const slug = args.slug.trim();
    const fallback = fallbackSkill(slug);
    const brain = await viewerBrainOrDefault(ctx);
    if (!brain) return fallback ? [toPublicSkill(null, fallback)] : [];

    const stored = await ctx.db
      .query("harnessSkills")
      .withIndex("by_brain_slug", (q: any) => q.eq("brainInstanceId", brain._id).eq("slug", slug))
      .collect();
    const publicStored = stored
      .filter((skill) => skill.visibility === "public")
      .sort((a, b) => b.version - a.version)
      .map((skill) => toPublicSkill(skill));

    if (publicStored.length > 0) return publicStored;
    return fallback ? [toPublicSkill(null, fallback)] : [];
  },
});

export const saveSkillForViewer = mutationGeneric({
  args: {
    slug: v.string(),
    title: v.string(),
    description: v.optional(v.string()),
    body: v.string(),
    usageDescription: v.optional(v.string()),
    usageLeadIn: v.optional(v.string()),
    schedulerInstructions: v.optional(v.string()),
    visibility: v.optional(v.union(v.literal("public"), v.literal("private"))),
  },
  handler: async (ctx, args) => {
    const { user, brain } = await requireOwnedBrain(ctx);
    const slug = args.slug.trim();
    const title = args.title.trim();
    const body = args.body.trim();
    if (!slug) throw new Error("skill slug is required");
    if (!title) throw new Error("skill title is required");
    if (!body) throw new Error("skill body is required");

    const now = Date.now();
    const existing = await currentSkill(ctx.db, brain._id, slug);
    if (existing) {
      await ctx.db.patch(existing._id, { isCurrent: false, updatedAt: now });
    }

    const skillId = await ctx.db.insert("harnessSkills", {
      brainInstanceId: brain._id,
      slug,
      title,
      description: args.description?.trim() || undefined,
      body,
      usageDescription:
        args.usageDescription?.trim() || existing?.usageDescription || fallbackSkill(slug)?.usageDescription,
      usageLeadIn: args.usageLeadIn?.trim() || existing?.usageLeadIn || fallbackSkill(slug)?.usageLeadIn,
      schedulerInstructions:
        args.schedulerInstructions?.trim() || existing?.schedulerInstructions || fallbackSkill(slug)?.schedulerInstructions,
      visibility: args.visibility ?? existing?.visibility ?? fallbackSkill(slug)?.visibility ?? "public",
      version: (existing?.version ?? fallbackSkill(slug)?.version ?? 0) + 1,
      isCurrent: true,
      createdByUserId: user._id,
      createdAt: now,
      updatedAt: now,
    });

    await ctx.db.insert("activityEvents", {
      brainInstanceId: brain._id,
      entityRef: { entityType: "knowledgeObject", entityId: skillId },
      activityType: "harness_skill_updated",
      actorType: "user",
      actorId: user._id,
      timestamp: now,
      summary: `Updated harness skill: ${title}`,
      metadata: { slug },
    });

    return { skillId, slug, status: "saved" };
  },
});
