import { mutationGeneric, queryGeneric } from "convex/server";
import { v } from "convex/values";
import { requireOwnedBrain } from "./auth";

const TASK_HEARTBEAT_BODY = [
  "# Skippy Task Heartbeat",
  "",
  "Check Skippy for requested Ready agent tasks using `list_requested_ready_tasks`.",
  "",
  "If no tasks are queued, stop quietly.",
  "",
  "If tasks are queued, process all queued tasks that can be completed safely in this wake.",
  "",
  "For each task:",
  "- Before doing meaningful work, mark the task in progress.",
  "- Execute it according to its execution brief and acceptance criteria.",
  "- Run relevant verification.",
  "- Report the result back to Skippy with `record_task_result` so the task moves to In Review.",
  "",
  "For coding tasks in projects with a GitHub repo:",
  "- Create or reuse a dedicated branch named `agent/task-<taskId>-<slug>`.",
  "- Commit only task-owned files.",
  "- Push the branch.",
  "- Create or reuse a GitHub PR.",
  "- Include `gitBranchName`, `prUrl`, `prNumber`, `prStatus`, and `resultUrl` when recording the task result.",
  "",
  "If the project has no repo configured, do not attempt branch/PR work; record a clear result or blocker message instead.",
  "",
  "Do not mark tasks done unless the owner explicitly requested automatic completion.",
  "",
  "If a task becomes blocked or unsafe to continue, record a clear result or status for that task and continue with the next queued task only when it is independent and safe to do so.",
].join("\n");

const TASK_HEARTBEAT_USAGE_DESCRIPTION =
  "Use this skill when you want an AI harness like Codex, Claude, or Hermes to periodically check Skippy for Ready agent tasks and report results back to Skippy.";

const TASK_HEARTBEAT_SCHEDULER_INSTRUCTIONS = [
  "If you support Skippy MCP prompts:",
  "Use the prompt `skippy_task_heartbeat`.",
  "",
  "If you do not support Skippy MCP prompts but do support Skippy MCP tools:",
  "Call `get_skill` with slug `task-heartbeat`",
  "",
  "If neither of those work, load the Skippy skill at:",
  "https://skippy.jeffschram.dev/skills/task-heartbeat",
].join("\n");

const HARNESS_BOOTSTRAP_BODY = [
  "# Skippy Harness Bootstrap",
  "",
  "You are an AI harness connected to Skippy MCP. Skippy is the user's portable second brain, project manager, and review layer. The harness supplies context and execution; Skippy stores accepted knowledge, tasks, project state, source references, and task results.",
  "",
  "## Key URLs And Endpoints",
  "",
  "- Production app: https://skippy.jeffschram.dev",
  "- Production MCP endpoint: https://skippy.jeffschram.dev/api/mcp",
  "- Local development app/MCP endpoint: http://localhost:3000 and http://localhost:3000/api/mcp",
  "",
  "## Auth Expectations",
  "",
  "- Use a Skippy MCP bearer token generated by the signed-in user.",
  "- Never print, store in chat, commit, or log raw tokens.",
  "- A token maps to one Skippy brain through Convex `mcpTokens`.",
  "",
  "## First 5 Minutes",
  "",
  "1. Confirm you can access Skippy MCP tools.",
  "2. Load this bootstrap skill and, when useful, `skippy_task_heartbeat`.",
  "3. Call `get_current_context` if the user says this project, here, or current project.",
  "4. Use `list_ready_tasks` or `list_requested_ready_tasks` before executing agent work.",
  "5. Fetch details with `get_task_brief`, do the work, verify it, then call `record_task_result`.",
  "",
  "## Core Workflow",
  "",
  "- Proposed tasks stay Proposed until promoted/briefed by Skippy or the owner.",
  "- Ready is the agent queue; requested Ready tasks are the safest automation queue.",
  "- Agent work should end in `in_review` unless the owner explicitly allows automatic completion.",
  "- Coding tasks should produce a branch, verification, and PR when the project has a GitHub repo.",
  "",
  "## Key Tools",
  "",
  "- `get_current_context`: resolve active app route/project.",
  "- `create_task` / `create_project`: explicit user-created items.",
  "- `plan_project`: decompose accepted projects.",
  "- `list_ready_tasks` / `list_requested_ready_tasks`: find executable work.",
  "- `get_task_brief`: get the handoff brief.",
  "- `record_task_result`: report PR/artifact/result for review.",
  "- `get_skill`: load canonical Skippy-hosted skills by slug.",
  "- `get_importance_rubric`, `ingest_object`, `record_memory`, `capture_thought`: capture useful second-brain context.",
  "",
  "## Canonical References",
  "",
  "- `README.md`: repo overview.",
  "- `docs/codex-heartbeat.md`: Ready task heartbeat contract.",
  "- `docs/onboarding-harness-verification.md`: onboarding and connection verification design.",
  "- `skills/skippy-harness/SKILL.md`: local Codex skill for Skippy harness behavior.",
  "- `apps/mcp-server/src/mcp-server.ts`: MCP prompts/resources/tools.",
  "- `apps/web/app/api/mcp/route.ts`: remote MCP endpoint.",
  "- `convex/mcpTokens.ts`: bearer-token auth.",
  "- `convex/projects.ts`: project/task planning and result state.",
].join("\n");

const HARNESS_BOOTSTRAP_USAGE_DESCRIPTION =
  "Use this skill when connecting a new AI harness so it can quickly understand Skippy, the MCP endpoint, auth expectations, and the project/task workflow.";

const HARNESS_BOOTSTRAP_SCHEDULER_INSTRUCTIONS = [
  "If you support Skippy MCP prompts:",
  "Use the prompt `skippy_harness_bootstrap`.",
  "",
  "If you do not support Skippy MCP prompts but do support Skippy MCP tools:",
  "Call `get_skill` with slug `harness-bootstrap`.",
  "",
  "If neither of those work, load the Skippy skill at:",
  "https://skippy.jeffschram.dev/skills/harness-bootstrap",
].join("\n");

const AGENDA_INGESTION_BODY = [
  "# Skippy Agenda Ingestion",
  "",
  "You are running as the **Agenda Agent** (role key: `agenda`). The role is defined by this skill; the harness executing it (Codex, Claude, Hermes) is interchangeable. See `docs/agents.md` for the agents-as-roles architecture.",
  "",
  "The job: read the user's sources, apply the importance rubric, store what matters as accepted Skippy objects with provenance, and refresh the focus summary. Coordinate through shared Skippy state only — never assume another agent will be messaged.",
  "",
  "## Run Protocol",
  "",
  "1. Call `update_source_sync_status` with status `running`, harness set to your engine name, and the sources in scope (for example `gmail`, `calendar`, `imessage`). Include `metadata.role: \"agenda\"`.",
  "2. Call `get_importance_rubric` and read `renderedText` before judging any item.",
  "3. Read the sources in scope since the last successful run. Also call `list_quick_captures` for pending Home quick captures — they are part of every ingestion pass.",
  "4. For each item, decide under the rubric:",
  "   - **Store**: clear deadline, money, commitment, relationship, focus-relevant, or security signal. Use `ingest_object` with a specific `rubricDecision` and at least one `sourceRef` (IDs, timestamp, one-line summary, shortest useful excerpt — never raw bodies).",
  "   - **Review**: genuinely uncertain but inspectable later. Use `submit_candidate_object`.",
  // 2026-08-30: added after Knowmad beta feedback from a group text was stored as a
  // floating review candidate instead of landing on the project it was clearly about.
  "   - **Project-linked**: when an item clearly references one of the user's live projects (the rubric lists them), don't leave it floating — ingest the note, then `link_entities` (`belongs_to`) it to that project so feedback, ideas, and status land on the project itself. Only create a project task when the item is specifically actionable (a bug report, an explicitly requested change); suggestions, opinions, and half-formed ideas stay as notes on the project.",
  "   - **Ignore**: marketing, newsletters, shipping notices, generic confirmations, transient alerts, secrets/credentials. Write nothing.",
  "   - Durable preferences, decisions, or principles evidenced by a source go through `record_memory` / `record_decision` / `record_principle` with provenance.",
  "5. For each pending quick capture, create the useful objects, then call `mark_quick_capture_handled` with `processed` (listing `relatedEntityRefs` you created) or `discarded` with a short note.",
  "6. Call `refresh_focus_summary` so the dashboard reflects the new state.",
  "7. Call `record_ingestion_run` with sources checked, object counts, errors, and `metadata.role: \"agenda\"`.",
  "8. Call `update_source_sync_status` with `completed` (or `failed` plus short error summaries). For long runs, heartbeat with `lastHeartbeatAt` while work continues.",
  "",
  "## Attribution",
  "",
  "Every run this skill performs is attributed to the `agenda` role, separate from the harness. Always set `metadata.role: \"agenda\"` on `record_ingestion_run` and `update_source_sync_status` so runs read as \"the Agenda Agent ran on <harness>\".",
  "",
  "## Boundaries",
  "",
  "- Ingestion and memory tools only: do not execute agent tasks, write financial data, or perform external side effects. Anything with side effects belongs in the approval-gated pending-actions flow.",
  "- Store distilled summaries with source refs, not raw private dumps.",
  "- Sensitive items (health, legal, family, private third-party facts) are never silently stored; queue for review or skip.",
  "- If a source is unreachable, record the error on the run and continue with the remaining sources; never fail silently.",
].join("\n");

const AGENDA_INGESTION_USAGE_DESCRIPTION =
  "Use this skill for scheduled Agenda Agent runs: reading gmail/calendar/imessage and pending quick captures, applying the importance rubric, ingesting accepted objects with provenance, and refreshing the focus summary.";

const AGENDA_INGESTION_SCHEDULER_INSTRUCTIONS = [
  "If you support Skippy MCP prompts:",
  "Use the prompt `skippy_agenda_ingestion`.",
  "",
  "If you do not support Skippy MCP prompts but do support Skippy MCP tools:",
  "Call `get_skill` with slug `agenda-ingestion`",
  "",
  "If neither of those work, load the Skippy skill at:",
  "https://skippy.jeffschram.dev/skills/agenda-ingestion",
].join("\n");

const FINANCE_SYNC_BODY = [
  "# Skippy Finance Sync",
  "",
  "You are running as the **Financial Agent** (role key: `finance`). The role is defined by this skill; the harness executing it is interchangeable. See `docs/agents.md` for the agents-as-roles architecture and `docs/plaid-financial-source.md` for the Plaid server setup and security posture.",
  "",
  "The job: sync bank data from the local read-only Plaid MCP server into Skippy's financial tables. Plaid data is **ground truth** — record it directly, never queue it for review. The judgment this skill canonicalizes is the mapping from raw Plaid data to the fixed Conscious Spending Plan (CSP) taxonomy.",
  "",
  "## Run Protocol",
  "",
  "1. Call `update_source_sync_status` with status `running`, statusKey `plaid-sync`, harness set to your engine name, sources `[\"plaid\"]`, and `metadata.role: \"finance\"`.",
  "2. **Accounts**: for each linked account, call `upsert_financial_account` with the Plaid `account_id` as `plaidAccountId` so re-syncs update rather than duplicate. `mask` is the LAST 4 characters only — never full account numbers. `accountType` is `Jeff Personal` or `Family Shared`.",
  "3. **Transactions**: fetch the raw feed and call `record_financial_transactions` with Plaid `transaction_id`s as `externalId`s (idempotent: existing IDs update in place). Amounts are integer cents, positive magnitudes; `txType` determines direction.",
  "4. **Balances**: call `record_financial_balances` with end-of-day snapshots computed by walking the FULL raw Plaid feed backward from the `/accounts/balance/get` current balance — including feed rows not recorded as budget transactions. NEVER derive balances by summing recorded budget transactions.",
  "5. Call `record_ingestion_run` with sources `[\"plaid\"]`, counts, errors, and `metadata.role: \"finance\"`.",
  "6. Call `update_source_sync_status` with `completed` (or `failed` plus short error summaries).",
  "",
  "## CSP Mapping Judgment",
  "",
  "Map each transaction to the FIXED type-category taxonomy (invalid pairs are rejected server-side):",
  "",
  "- **Fixed Costs**: `Mortgage, HOA, Mortgage Loan` | `Recurring Bills` | `Debt Payments` | `Groceries` | `Subscriptions`",
  "- **Investments**: `Retirement` | `Brokerage`",
  "- **Savings**: `Emergency Fund` | `Goals`",
  "- **Guilt-Free**: `Restaurants` | `Gas, Amazon, Home Depot, Etc` | `Misc.`",
  "- **Income**: `Jeff` | `Holly`",
  "- **Transfer**: `Transfers In` | `Transfers Out`",
  "",
  "Rules that override merchant-name intuition:",
  "",
  "- **Transfer detection**: money moving between the owner's own accounts — tracked or untracked, including business checking or a partner's external account — is txType `Transfer` with `Transfers In`/`Transfers Out`. Never Income, never an outgoing bucket. Transfers are excluded from budget totals automatically.",
  "- **Off-ledger 401k**: payroll-deducted retirement contributions that never touch checking are `offLedger: true` (txType `Investments` only) with `contributionSource`: `employee` amounts are the owner's pre-tax pay and gross up the percent-of-income denominator for CSP targets; `employer` match counts in Investments totals but is NOT income and never grosses up the denominator.",
  "- **Merchant judgment**: grocery stores map to `Groceries`; restaurants and coffee to `Restaurants`; gas, Amazon, and home improvement to `Gas, Amazon, Home Depot, Etc`; recognized paychecks to `Income` under the correct earner (`Jeff` or `Holly`). When genuinely ambiguous, prefer `Guilt-Free` / `Misc.` over inventing a fixed cost.",
  "",
  "## Attribution",
  "",
  "Every run is attributed to the `finance` role, separate from the harness. Always set `metadata.role: \"finance\"` on `record_ingestion_run` and `update_source_sync_status` so runs read as \"the Financial Agent ran on <harness>\".",
  "",
  "## Boundaries",
  "",
  "- Financial tools and run bookkeeping only: no task execution, no general source ingestion, no external side effects.",
  "- The Plaid server is read-only; never attempt money movement, item modification, or write endpoints.",
  "- Never print, log, or store Plaid secrets or access tokens; they stay in the local chmod-600 config.",
  "- Sandbox credentials only for automated runs; production credentials require an explicit owner-approved task.",
  "- Record structured budget data, not prose dumps. Notable anomalies (fraud-shaped charges, missed payroll, failed autopay) may additionally be ingested as concise Skippy objects with `sourceSystem: \"plaid\"` sourceRefs.",
].join("\n");

const FINANCE_SYNC_USAGE_DESCRIPTION =
  "Use this skill for scheduled Financial Agent runs: syncing accounts, transactions, and balances from the local read-only Plaid MCP server into Skippy under the fixed CSP taxonomy.";

const FINANCE_SYNC_SCHEDULER_INSTRUCTIONS = [
  "If you support Skippy MCP prompts:",
  "Use the prompt `skippy_finance_sync`.",
  "",
  "If you do not support Skippy MCP prompts but do support Skippy MCP tools:",
  "Call `get_skill` with slug `finance-sync`",
  "",
  "If neither of those work, load the Skippy skill at:",
  "https://skippy.jeffschram.dev/skills/finance-sync",
].join("\n");

const PROJECT_MANAGER_BODY = [
  "# Skippy Project Manager",
  "",
  "You are running as the **Project Manager Agent** for ONE project (role key: `pm:{projectId}`). This is the single project-manager skill parameterized by projectId; the harness executing it is interchangeable. See `docs/agents.md` for the agents-as-roles architecture and `docs/project-manager-agent.md` for the full design.",
  "",
  "The job: keep one project's plan healthy between owner sessions. Review finished work, brief proposed tasks against the actual repo, flag what is stuck or stale, and tell the owner what deserves attention — without taking any action the owner would want to take themselves.",
  "",
  "## Inputs",
  "",
  "You are invoked with a `projectId`. If invoked without one, resolve the active project via `get_current_context`; if none resolves, stop quietly.",
  "",
  "## Run Protocol",
  "",
  "1. **Gather state (read-only)**: `get_project_plan` for phases/tasks/states; `list_tasks_by_state` for `in_review`, `blocked`, `in_progress`, and `proposed` scoped to the project; `get_project_notes` for context only — NEVER edit the notes pad. Read the project repo when a local checkout is available; repo grounding is required for briefs.",
  "2. **Review results**: for each `in_review` task, read `resultSummary`, PR status, and artifacts, and distill what the owner needs to know to approve or reject — one or two sentences, not a restatement. Record via `record_entity_review` on the task with `reviewType: \"status_check\"`. Never approve, reject, or mark tasks done.",
  "3. **Brief proposed tasks**: for `proposed` tasks, write grounded execution briefs with `brief_task` — concrete files, existing patterns, verification steps. Skip tasks too vague to brief honestly and flag them in the digest instead of inventing scope. Skip tasks already briefed this cycle.",
  "4. **Flag blocked and stale work**: for `blocked` tasks, check whether the stated blocker still holds; if evidently unblocked, say so in the digest — do not change state. Flag `in_progress` tasks idle beyond 7 days and `in_review` tasks untouched beyond 3 days via `record_entity_review` with `reviewType: \"stale_check\"`.",
  "5. **Notice plan/reality divergence**: compare the Plan against the repo and task states. Divergence is reported in the digest, never repaired — do not edit phases, reorder plans, or move tasks.",
  "6. **Suggest promotions**: list briefed tasks that look ready, with one-line reasons. Promotion to Ready stays an owner action.",
  "7. **Digest + bookkeeping**: record a concise digest via `record_entity_review` on the PROJECT with `reviewType: \"general\"` — sections: results awaiting review, briefs written, flags, suggested promotions; omit empty sections. Then `record_ingestion_run` with `sourceSystemsChecked: [\"skippy\"]` and `metadata.role: \"pm:{projectId}\"`. If there was nothing to do after step 1, record nothing and stop quietly.",
  "",
  "## Boundaries",
  "",
  "Allowed without approval: `brief_task`, `record_entity_review` (task reviews, stale/blocker flags, priority scores with reasons, project digest), run bookkeeping.",
  "",
  "Report-only (digest lines): promotion recommendations, plan/reality divergence, unblock observations, result summaries.",
  "",
  "Never: promote tasks to Ready, approve/complete/cancel tasks, edit the notes pad or phase descriptions, or perform external side effects (push, PR, email — anything approval-gated).",
  "",
  "Rule of thumb: mutate only what is safe, reversible, and inside Skippy state, and only in ways that ADD information rather than change decisions. Everything decision-shaped is a digest line.",
  "",
  "## Attribution And Failure",
  "",
  "- Attribute every run with `metadata.role: \"pm:{projectId}\"` so it reads as \"PM: {project} ran on <harness>\".",
  "- Per-project isolation: when running PM passes for multiple projects, one project's failure must not abort the others.",
  "- Errors land on the run record's `errors` array; never fail silently.",
  "- Be idempotent per day: re-running after a crash re-reads state and re-writes at most the same digest.",
].join("\n");

const PROJECT_MANAGER_USAGE_DESCRIPTION =
  "Use this skill for scheduled Project Manager Agent runs: one pass per active project that reviews task results, briefs proposed tasks against the repo, flags blocked/stale work, and records an owner-facing digest.";

const PROJECT_MANAGER_SCHEDULER_INSTRUCTIONS = [
  "Run nightly, once per project with status in_progress. For each project pass its projectId.",
  "",
  "If you support Skippy MCP prompts:",
  "Use the prompt `skippy_project_manager`.",
  "",
  "If you do not support Skippy MCP prompts but do support Skippy MCP tools:",
  "Call `get_skill` with slug `project-manager`",
  "",
  "If neither of those work, load the Skippy skill at:",
  "https://skippy.jeffschram.dev/skills/project-manager",
].join("\n");

// Reference skills below hold the long-form guidance that used to live inside
// MCP tool descriptions. Every harness session pays for tool descriptions on
// connect, but skills are fetched on demand via get_skill, so essay-length
// rules belong here (docs/token-efficiency.md, Stage 2).

const FINANCE_TAXONOMY_BODY = [
  "# Skippy Finance Taxonomy (CSP)",
  "",
  "Reference for `record_financial_transactions`, `record_financial_balances`, and `upsert_financial_account`. Plaid data is ground truth: ingest it directly, never queue it for review. All amounts are INTEGER CENTS (positive magnitudes; txType determines direction).",
  "",
  "## Fixed type-category taxonomy",
  "",
  "Type-category pairing is enforced server-side; invalid pairs are rejected:",
  "",
  "- **Fixed Costs**: `Mortgage, HOA, Mortgage Loan` | `Recurring Bills` | `Debt Payments` | `Groceries` | `Subscriptions`",
  "- **Investments**: `Retirement` | `Brokerage`",
  "- **Savings**: `Emergency Fund` | `Goals`",
  "- **Guilt-Free**: `Restaurants` | `Gas, Amazon, Home Depot, Etc` | `Misc.`",
  "- **Income**: `Jeff` | `Holly`",
  "- **Transfer**: `Transfers In` | `Transfers Out`",
  "",
  "## Rules that override merchant-name intuition",
  "",
  "- **Transfers**: money moving between the owner's own accounts — tracked or untracked, including business checking or a partner's external account — is txType `Transfer` with `Transfers In`/`Transfers Out`. Never Income, never an outgoing bucket. For Transfer the category IS the direction. Transfers are excluded from budget totals automatically.",
  "- **Off-ledger 401k**: payroll-deducted retirement contributions that never touch checking are `offLedger: true` (txType `Investments` only) and require `contributionSource`. `employee` amounts are the owner's pre-tax pay and gross up the percent-of-income denominator used for CSP budget targets; `employer` match counts in Investments totals but is NOT income and never grosses up the denominator. Off-ledger rows are excluded from outgoing/net and from account balances.",
  "- **Merchant judgment**: grocery stores map to `Groceries`; restaurants and coffee to `Restaurants`; gas, Amazon, and home improvement to `Gas, Amazon, Home Depot, Etc`; recognized paychecks to `Income` under the correct earner. When genuinely ambiguous, prefer `Guilt-Free` / `Misc.` over inventing a fixed cost.",
  "",
  "## Idempotency",
  "",
  "- Transactions: pass Plaid transaction_ids as `externalId` — an existing externalId updates the stored transaction instead of duplicating it. Returns {inserted, updated, skipped}.",
  "- Accounts: pass the Plaid account_id as `plaidAccountId` so re-syncs update the same account. `mask` is the LAST 4 characters of the account number ONLY — never send full account numbers.",
  "- Balances: one snapshot per account+day; re-sending a day updates it. Returns {inserted, updated}.",
  "",
  "## Balance derivation",
  "",
  "Compute end-of-day balances from the FULL raw Plaid transaction feed walked backward from the `/accounts/balance/get` current balance — including feed rows not recorded as budget transactions. NEVER derive balances by summing recorded budget transactions. Balances may be negative.",
].join("\n");

const FINANCE_TAXONOMY_USAGE_DESCRIPTION =
  "Reference skill for the fixed Conscious Spending Plan taxonomy: type-category pairing, transfer rules, off-ledger 401k semantics, idempotency keys, and balance derivation.";

const FINANCE_TAXONOMY_SCHEDULER_INSTRUCTIONS = [
  "Before recording financial data with Skippy MCP tools:",
  "Call `get_skill` with slug `finance-taxonomy`",
  "",
  "If that does not work, load the Skippy skill at:",
  "https://skippy.jeffschram.dev/skills/finance-taxonomy",
].join("\n");

const MEMORY_RUBRIC_BODY = [
  "# Skippy Memory And Importance Rubric",
  "",
  "Reference for the memory and ingestion write tools: `record_memory`, `record_decision`, `record_principle`, `capture_thought`, `submit_memory_review_candidate`, `ingest_object`, `submit_candidate_object`, and the `upsert_*` convenience tools.",
  "",
  "## Choosing a write path",
  "",
  "- **record_memory / record_decision / record_principle**: direct durable writes when you can explain why the item belongs. `memory` = stable preference, personal fact, or recurring context; `decision` = a choice, direction, or tradeoff clearly established; `principle` = durable operating rule about how Skippy or harnesses should behave, not a one-off observation. Direct memory writes require a `rubricDecision` explaining why the item clears the rubric.",
  "- **capture_thought**: an explicit user thought to remember; `reviewBehavior` picks direct write vs review queue.",
  "- **submit_memory_review_candidate**: only when genuinely unsure an item should be stored. Unreviewed candidates auto-archive after 14 days, so only queue items worth a durable memory.",
  "- **ingest_object**: the primary write for source-derived typed knowledge (task, person, link, note, ...). Include `sourceRefs` and a concise `rubricDecision` naming the signal: deadline, money, relationship, commitment, focus relevance, security.",
  "- **submit_candidate_object**: legacy fallback when you cannot decide whether a source item clears the rubric.",
  "",
  "## What NOT to store",
  "",
  "Never queue transient alerts — balance notifications, promo deadlines, ToS/policy notices, expiring offers. Skip them, or if genuinely useful, record directly with expiry context in the body. Do not store full raw emails or long private source text; sourceRef excerpts are short quotes only.",
  "",
  "## Links",
  "",
  "Links are reference material: status defaults to `saved` (no user interaction expected). Pass `unread` only for explicit read-later intent. If genuinely uncertain a link is valid or important, use submit_candidate_object so it lands in Review for a one-tap decision. `update_link_status` is for genuine lifecycle changes only — never fake user engagement.",
  "",
  "## Provenance",
  "",
  "Source-backed writes carry `sourceRefs` (sourceSystem plus IDs/links/excerpt). Related entity refs must be accepted entity IDs, never fallback review item IDs.",
].join("\n");

const MEMORY_RUBRIC_USAGE_DESCRIPTION =
  "Reference skill for deciding what belongs in Skippy memory and accepted knowledge: write-path selection, rubricDecision expectations, transient-alert exclusions, link status defaults, and provenance rules.";

const MEMORY_RUBRIC_SCHEDULER_INSTRUCTIONS = [
  "Before writing memories or ingesting source-derived knowledge with Skippy MCP tools:",
  "Call `get_skill` with slug `memory-rubric`",
  "",
  "If that does not work, load the Skippy skill at:",
  "https://skippy.jeffschram.dev/skills/memory-rubric",
].join("\n");

const FILE_UPLOAD_BODY = [
  "# Skippy Project File Upload Protocol",
  "",
  "Reference for the project library tools. Convex records are canonical; any local paths are temporary runner copies. Download URLs are always ephemeral — download promptly, never persist them.",
  "",
  "## Simple 2-step upload (chat/harness flow)",
  "",
  "1. `generate_project_file_upload_url` — returns a short-lived, single-use Convex storage POST URL (not project-scoped).",
  "2. HTTP POST the raw file bytes to that URL with the file's Content-Type header; the response JSON contains `{storageId}`.",
  "3. `register_project_file` with that storageId plus projectId, fileName, mimeType, and sizeBytes.",
  "",
  "Limits: max 25 MB (26214400 bytes). Allowed types: images, PDFs, text (plain/markdown/csv), JSON, and common office documents. Executables and arbitrary binaries are rejected.",
  "",
  "## Canonical task-run upload (begin/finalize/abort)",
  "",
  "For task runs producing durable artifacts, use `begin_project_file_upload` (creates a pending record with a stable fileId; reuse `uploadKey` when retrying the same logical upload), POST the bytes, then `finalize_project_file_upload` with storageId and SHA-256 (idempotent on replay). On failure, `abort_project_file_upload` marks the record failed and removes the orphan blob.",
  "",
  "## Library semantics",
  "",
  "- At task start, materialize needed library files into the project's effectiveAssetsPath (the `_library` folder) before working, skipping files already present locally with a matching size.",
  "- Files found only locally are NOT in the library until registered.",
  "- `list_project_files` / `get_project_file_manifest` list canonical records with fresh ephemeral URLs; `get_project_file` resolves one stable fileId.",
  "- Attach task outputs by passing taskId at registration and reporting `artifactFileIds` in `record_task_result`.",
].join("\n");

const FILE_UPLOAD_USAGE_DESCRIPTION =
  "Reference skill for the cloud-canonical project library: the 2-step upload protocol, the begin/finalize/abort task-run flow, size/type limits, and materialize/register semantics.";

const FILE_UPLOAD_SCHEDULER_INSTRUCTIONS = [
  "Before uploading or materializing project files with Skippy MCP tools:",
  "Call `get_skill` with slug `file-upload`",
  "",
  "If that does not work, load the Skippy skill at:",
  "https://skippy.jeffschram.dev/skills/file-upload",
].join("\n");

const RECURRENCE_SEMANTICS_BODY = [
  "# Skippy Recurrence Semantics",
  "",
  "Reference for `upsert_recurrence`, `complete_recurrence`, and `list_recurrences`.",
  "",
  "## When to use a recurrence",
  "",
  "Use a recurrence — not a task with a due date — for anything that comes around again: furnace filter, oil change, rent, trash night, annual renewals. Completing a task destroys the record of when it was last done, which is usually the fact worth keeping.",
  "",
  "## Anchor semantics (this changes behavior)",
  "",
  "- **completion**: the next due date is measured from when the work is actually finished. Maintenance behaves this way — do it five weeks late and the cadence shifts with you.",
  "- **schedule**: a fixed calendar date that ignores completion. Bills and dues behave this way.",
  "",
  "Because of this, `completedAt` on `complete_recurrence` is not cosmetic: backdating ('I did this last Tuesday') directly determines the next due date for completion-anchored recurrences.",
  "",
  "## Rules",
  "",
  "Two rule kinds:",
  "",
  "- **interval**: every N days (`{ kind: \"interval\", everyDays: N }`).",
  "- **calendar**: a supported RRULE subset — `FREQ=DAILY|WEEKLY|MONTHLY|YEARLY` with optional `INTERVAL`, `BYDAY`, `BYMONTHDAY`, `BYMONTH` (`{ kind: \"calendar\", rrule: \"FREQ=MONTHLY;BYMONTHDAY=1\" }`).",
  "",
  "Wall-clock schedules anchor to the `timeZone` IANA zone; `leadTimeDays` surfaces the item early.",
  "",
  "## Task spawning",
  "",
  "`spawnTask: true` (the default) materializes a real task when due — chores want this. `spawnTask: false` keeps the item agenda-only — ambient things like trash night. In `list_agenda`, a recurrence that already spawned a task appears once, as the task.",
].join("\n");

const RECURRENCE_SEMANTICS_USAGE_DESCRIPTION =
  "Reference skill for recurring obligations: completion vs schedule anchors, the supported RRULE subset, backdated completions, and task spawning behavior.";

const RECURRENCE_SEMANTICS_SCHEDULER_INSTRUCTIONS = [
  "Before creating or completing recurrences with Skippy MCP tools:",
  "Call `get_skill` with slug `recurrence-semantics`",
  "",
  "If that does not work, load the Skippy skill at:",
  "https://skippy.jeffschram.dev/skills/recurrence-semantics",
].join("\n");

const DEFAULT_SKILLS = [
  {
    slug: "task-heartbeat",
    title: "Task heartbeat",
    description: "Portable instructions for harnesses that execute requested Ready agent tasks from Skippy.",
    body: TASK_HEARTBEAT_BODY,
    usageDescription: TASK_HEARTBEAT_USAGE_DESCRIPTION,
    usageLeadIn: "In your harness scheduler paste the following:",
    schedulerInstructions: TASK_HEARTBEAT_SCHEDULER_INSTRUCTIONS,
    visibility: "public" as const,
    version: 1,
  },
  {
    slug: "harness-bootstrap",
    title: "Harness bootstrap",
    description: "Portable context pack that teaches a newly connected harness how Skippy works.",
    body: HARNESS_BOOTSTRAP_BODY,
    usageDescription: HARNESS_BOOTSTRAP_USAGE_DESCRIPTION,
    usageLeadIn: "Give a newly connected harness this instruction:",
    schedulerInstructions: HARNESS_BOOTSTRAP_SCHEDULER_INSTRUCTIONS,
    visibility: "public" as const,
    version: 1,
  },
  {
    slug: "agenda-ingestion",
    title: "Agenda ingestion",
    description:
      "The Agenda Agent's role skill: rubric-driven source ingestion with provenance, quick-capture handling, sync status, and focus refresh.",
    body: AGENDA_INGESTION_BODY,
    usageDescription: AGENDA_INGESTION_USAGE_DESCRIPTION,
    usageLeadIn: "In your harness scheduler paste the following:",
    schedulerInstructions: AGENDA_INGESTION_SCHEDULER_INSTRUCTIONS,
    visibility: "public" as const,
    version: 2,
  },
  {
    slug: "finance-sync",
    title: "Finance sync",
    description:
      "The Financial Agent's role skill: Plaid account/transaction/balance sync into Skippy under the fixed CSP taxonomy, with transfer and off-ledger 401k rules.",
    body: FINANCE_SYNC_BODY,
    usageDescription: FINANCE_SYNC_USAGE_DESCRIPTION,
    usageLeadIn: "In your harness scheduler paste the following:",
    schedulerInstructions: FINANCE_SYNC_SCHEDULER_INSTRUCTIONS,
    visibility: "public" as const,
    version: 1,
  },
  {
    slug: "project-manager",
    title: "Project manager",
    description:
      "The Project Manager Agent's role skill, parameterized by projectId: review task results, brief proposed tasks against the repo, flag blocked/stale work, and record an owner-facing digest.",
    body: PROJECT_MANAGER_BODY,
    usageDescription: PROJECT_MANAGER_USAGE_DESCRIPTION,
    usageLeadIn: "In your harness scheduler paste the following:",
    schedulerInstructions: PROJECT_MANAGER_SCHEDULER_INSTRUCTIONS,
    visibility: "public" as const,
    version: 1,
  },
  {
    slug: "finance-taxonomy",
    title: "Finance taxonomy",
    description:
      "Reference: the fixed CSP type-category taxonomy with transfer rules, off-ledger 401k semantics, idempotency keys, and balance derivation.",
    body: FINANCE_TAXONOMY_BODY,
    usageDescription: FINANCE_TAXONOMY_USAGE_DESCRIPTION,
    usageLeadIn: "To load this reference in a harness:",
    schedulerInstructions: FINANCE_TAXONOMY_SCHEDULER_INSTRUCTIONS,
    visibility: "public" as const,
    version: 1,
  },
  {
    slug: "memory-rubric",
    title: "Memory rubric",
    description:
      "Reference: which memory/ingestion write path to use, rubricDecision expectations, transient-alert exclusions, link status defaults, and provenance rules.",
    body: MEMORY_RUBRIC_BODY,
    usageDescription: MEMORY_RUBRIC_USAGE_DESCRIPTION,
    usageLeadIn: "To load this reference in a harness:",
    schedulerInstructions: MEMORY_RUBRIC_SCHEDULER_INSTRUCTIONS,
    visibility: "public" as const,
    version: 1,
  },
  {
    slug: "file-upload",
    title: "Project file upload",
    description:
      "Reference: the cloud-canonical project library — 2-step upload, begin/finalize/abort task-run flow, size/type limits, and materialize/register semantics.",
    body: FILE_UPLOAD_BODY,
    usageDescription: FILE_UPLOAD_USAGE_DESCRIPTION,
    usageLeadIn: "To load this reference in a harness:",
    schedulerInstructions: FILE_UPLOAD_SCHEDULER_INSTRUCTIONS,
    visibility: "public" as const,
    version: 1,
  },
  {
    slug: "recurrence-semantics",
    title: "Recurrence semantics",
    description:
      "Reference: recurring obligations — completion vs schedule anchors, the supported RRULE subset, backdated completions, and task spawning.",
    body: RECURRENCE_SEMANTICS_BODY,
    usageDescription: RECURRENCE_SEMANTICS_USAGE_DESCRIPTION,
    usageLeadIn: "To load this reference in a harness:",
    schedulerInstructions: RECURRENCE_SEMANTICS_SCHEDULER_INSTRUCTIONS,
    visibility: "public" as const,
    version: 1,
  },
];

function fallbackSkill(slug: string) {
  return DEFAULT_SKILLS.find((skill) => skill.slug === slug) ?? null;
}

async function viewerBrainOrDefault(ctx: any) {
  const identity = await ctx.auth.getUserIdentity();
  if (identity) {
    try {
      const { brain } = await requireOwnedBrain(ctx);
      return brain;
    } catch {
      // Fall through to the first brain so public skill pages remain readable locally.
    }
  }
  return await ctx.db.query("brainInstances").first();
}

async function currentSkill(db: any, brainInstanceId: string, slug: string) {
  return await db
    .query("harnessSkills")
    .withIndex("by_brain_slug_current", (q: any) =>
      q.eq("brainInstanceId", brainInstanceId).eq("slug", slug).eq("isCurrent", true),
    )
    .first();
}

function toPublicSkill(skill: any, fallback?: (typeof DEFAULT_SKILLS)[number]) {
  return {
    _id: skill?._id,
    slug: skill?.slug ?? fallback?.slug,
    title: skill?.title ?? fallback?.title,
    description: skill?.description ?? fallback?.description,
    body: skill?.body ?? fallback?.body,
    usageDescription: skill?.usageDescription ?? fallback?.usageDescription,
    usageLeadIn: skill?.usageLeadIn ?? fallback?.usageLeadIn,
    schedulerInstructions: skill?.schedulerInstructions ?? fallback?.schedulerInstructions,
    visibility: skill?.visibility ?? fallback?.visibility ?? "public",
    version: skill?.version ?? fallback?.version ?? 1,
    isDefault: !skill,
    updatedAt: skill?.updatedAt,
  };
}

export const listSkills = queryGeneric({
  args: {},
  handler: async (ctx) => {
    const brain = await viewerBrainOrDefault(ctx);
    if (!brain) return DEFAULT_SKILLS.map((skill) => toPublicSkill(null, skill));

    const stored = await ctx.db
      .query("harnessSkills")
      .withIndex("by_brain_current", (q: any) => q.eq("brainInstanceId", brain._id).eq("isCurrent", true))
      .collect();
    const bySlug = new Map(stored.map((skill: any) => [skill.slug, skill]));
    const merged = DEFAULT_SKILLS.map((skill) => toPublicSkill(bySlug.get(skill.slug), skill));
    for (const skill of stored) {
      if (!DEFAULT_SKILLS.some((defaultSkill) => defaultSkill.slug === skill.slug)) {
        merged.push(toPublicSkill(skill));
      }
    }
    return merged.filter((skill) => skill.visibility === "public");
  },
});

export const getSkill = queryGeneric({
  args: { slug: v.string() },
  handler: async (ctx, args) => {
    const slug = args.slug.trim();
    const fallback = fallbackSkill(slug);
    const brain = await viewerBrainOrDefault(ctx);
    if (!brain) return fallback ? toPublicSkill(null, fallback) : null;
    const stored = await currentSkill(ctx.db, brain._id, slug);
    const skill = toPublicSkill(stored, fallback ?? undefined);
    return skill.slug && skill.visibility === "public" ? skill : null;
  },
});

export const getSkillForBrain = queryGeneric({
  args: { brainInstanceId: v.id("brainInstances"), slug: v.string() },
  handler: async (ctx, args) => {
    const slug = args.slug.trim();
    const fallback = fallbackSkill(slug);
    const stored = await currentSkill(ctx.db, args.brainInstanceId, slug);
    return toPublicSkill(stored, fallback ?? undefined);
  },
});

export const listSkillVersions = queryGeneric({
  args: { slug: v.string() },
  handler: async (ctx, args) => {
    const slug = args.slug.trim();
    const fallback = fallbackSkill(slug);
    const brain = await viewerBrainOrDefault(ctx);
    if (!brain) return fallback ? [toPublicSkill(null, fallback)] : [];

    const stored = await ctx.db
      .query("harnessSkills")
      .withIndex("by_brain_slug", (q: any) => q.eq("brainInstanceId", brain._id).eq("slug", slug))
      .collect();
    const publicStored = stored
      .filter((skill) => skill.visibility === "public")
      .sort((a, b) => b.version - a.version)
      .map((skill) => toPublicSkill(skill));

    if (publicStored.length > 0) return publicStored;
    return fallback ? [toPublicSkill(null, fallback)] : [];
  },
});

export const saveSkillForViewer = mutationGeneric({
  args: {
    slug: v.string(),
    title: v.string(),
    description: v.optional(v.string()),
    body: v.string(),
    usageDescription: v.optional(v.string()),
    usageLeadIn: v.optional(v.string()),
    schedulerInstructions: v.optional(v.string()),
    visibility: v.optional(v.union(v.literal("public"), v.literal("private"))),
  },
  handler: async (ctx, args) => {
    const { user, brain } = await requireOwnedBrain(ctx);
    const slug = args.slug.trim();
    const title = args.title.trim();
    const body = args.body.trim();
    if (!slug) throw new Error("skill slug is required");
    if (!title) throw new Error("skill title is required");
    if (!body) throw new Error("skill body is required");

    const now = Date.now();
    const existing = await currentSkill(ctx.db, brain._id, slug);
    if (existing) {
      await ctx.db.patch(existing._id, { isCurrent: false, updatedAt: now });
    }

    const skillId = await ctx.db.insert("harnessSkills", {
      brainInstanceId: brain._id,
      slug,
      title,
      description: args.description?.trim() || undefined,
      body,
      usageDescription:
        args.usageDescription?.trim() || existing?.usageDescription || fallbackSkill(slug)?.usageDescription,
      usageLeadIn: args.usageLeadIn?.trim() || existing?.usageLeadIn || fallbackSkill(slug)?.usageLeadIn,
      schedulerInstructions:
        args.schedulerInstructions?.trim() || existing?.schedulerInstructions || fallbackSkill(slug)?.schedulerInstructions,
      visibility: args.visibility ?? existing?.visibility ?? fallbackSkill(slug)?.visibility ?? "public",
      version: (existing?.version ?? fallbackSkill(slug)?.version ?? 0) + 1,
      isCurrent: true,
      createdByUserId: user._id,
      createdAt: now,
      updatedAt: now,
    });

    await ctx.db.insert("activityEvents", {
      brainInstanceId: brain._id,
      entityRef: { entityType: "knowledgeObject", entityId: skillId },
      activityType: "harness_skill_updated",
      actorType: "user",
      actorId: user._id,
      timestamp: now,
      summary: `Updated harness skill: ${title}`,
      metadata: { slug },
    });

    return { skillId, slug, status: "saved" };
  },
});
